[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "djalthingi"
version = "0.1.3"
description = "Django app for retrieving, storing and handling Althingi's published XML data"
requires-python = ">=3.9"
dependencies = [
    "cloudscraper",
    "dateparser",
    "django>=4.0",
    "django-ninja",
    "icalendar",
    "lxml",
    "pytz",
    "requests",
    "unidecode",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["djalthingi*"]

[tool.setuptools.exclude-package-data]
djalthingi = ["xmlcache/*"]
