# Generated by Django 6.0.3 on 2026-03-12 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djalthingi", "0010_alter_minister_abbreviation_long"),
    ]

    operations = [
        migrations.AddField(
            model_name="parliament",
            name="last_full_update_version",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
